name: Run Shell Tests

on:
  pull_request:
    paths:
      - '**.sh'

concurrency:
  group: run-shell-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-shell-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run shell tests
        run: |
          bash tests/run_shell_tests.sh
